name: Build

on: [ pull_request, push, workflow_dispatch ]

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'build.gradle') }}
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Merge Fabric and Forge JARs
        run: |
          chmod +x gradlew
          ./gradlew mergeJars

      - name: Upload artifacts (fabric)
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: ${{ github.workspace }}/fabric/build/libs

      - name: Upload artifacts (forge)
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: ${{ github.workspace }}/forge/build/libs

      - name: Upload artifacts (neoforge)
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: ${{ github.workspace }}/neoforge/build/libs

      - name: Upload artifacts (Forgix merged jar)
        uses: actions/upload-artifact@v3
        with:
          name: merged
          path: ${{ github.workspace }}/build/libs/forgix